export type SET_CURRENT_TALKER = 'SET_CURRENT_TALKER'
export const SET_CURRENT_TALKER = 'SET_CURRENT_TALKER'
export const SET_RECEIVE_MSG = 'SET_RECEIVE_MSG'
export const ADD_RECEIVE_MSG = 'ADD_RECEIVE_MSG'
